1-VERİYİ YÜKLEME VE BOYUT KONTROLü

In [ ]:
import pandas as pd

#colab'e yüklediğim titanic verisinin csv dosyası okunuyor
#Passenger Id sütununu satır indeksi yapıyoruz (index_col ='PassengeId)

dosya_adi = "train_and_test2.csv"
df = pd.read_csv(dosya_adi, index_col="Passengerid")

#Burada csv dosytasını pandas dataframe'e aktardım
#satırlar yolcuları,sütunlar is yolculara ait özellikleri tutuyor

#satır sütun sayısını verir
print("Veri seti boyutu (Satır,Sütun):" , df.shape)

#ilk 5 satırı inceler
print("İlk 5 Gözlem:")
display(df.head())

Veri seti boyutu (Satır,Sütun): (1309, 27)
İlk 5 Gözlem:

,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,zero.5,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
Passengerid,,,,,,,,,,,,,,,,,,,,,
1,22.0,7.2500,0,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
2,38.0,71.2833,1,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
3,26.0,7.9250,1,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
4,35.0,53.1000,1,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
5,35.0,8.0500,0,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

2-VERİ TİPLERİ (DATA TYPES) VE EKSİK VERİ (MISSING VALUES) KONTROLÜ

In [ ]:
#her sütunun veri tipini topluca kontrol eder
print("Sütun Veri Tipleri")
print(df.dtypes)

#her sütundaki eksik değer saysını hesaplar
print("\n Eksik Veri Sayısı")
eksik_sayisi=df.isnull().sum()
print(eksik_sayisi[eksik_sayisi>0])
#burada boşluklar bulunuyor. Boşluklar modelde kullanılamaz
#ya doldurulmalı ya da satır sütun bazında eleme yapılmalı

Sütun Veri Tipleri
Age         float64
Fare        float64
Sex           int64
sibsp         int64
zero          int64
zero.1        int64
zero.2        int64
zero.3        int64
zero.4        int64
zero.5        int64
zero.6        int64
Parch         int64
zero.7        int64
zero.8        int64
zero.9        int64
zero.10       int64
zero.11       int64
zero.12       int64
zero.13       int64
zero.14       int64
Pclass        int64
zero.15       int64
zero.16       int64
Embarked    float64
zero.17       int64
zero.18       int64
2urvived      int64
dtype: object

 Eksik Veri Sayısı
Embarked    2
dtype: int64

3-İSTATİSTİKSEL ÖZETLER VE FREKANSLAR (DESCRIBE & VALUE_COUNTS)

In [ ]:
#sayısal sütunların özet istatistiklerini hesaplar
print("\n Sayısal Değişken İstatistiksel Özeti ")
display(df.describe())
#çıktı yorumlama
#burada yaş ortalaması 29.503186
#Fare min 0, max 512.329200	çıkmış bu değer aykırı değer olabileceğini gösteriyor


# Kategorik değişkenlerdeki sınıfların sayımı
print("\n Cinsiyet Dağılımı")
print(df['Sex'].value_counts())


#tekrar etmeyenlerin listesi
print("\n Benzersizler")
print(df['Embarked'].unique())

 Sayısal Değişken İstatistiksel Özeti

,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,zero.5,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
count,1309.000000,1309.000000,1309.000000,1309.000000,1309.0,1309.0,1309.0,1309.0,1309.0,1309.0,...,1309.0,1309.0,1309.0,1309.000000,1309.0,1309.0,1307.000000,1309.0,1309.0,1309.000000
mean,29.503186,33.281086,0.355997,0.498854,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.294882,0.0,0.0,1.492731,0.0,0.0,0.261268
std,12.905241,51.741500,0.478997,1.041658,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.837836,0.0,0.0,0.814626,0.0,0.0,0.439494
min,0.170000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.000000,0.0,0.0,0.000000,0.0,0.0,0.000000
25%,22.000000,7.895800,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.000000,0.0,0.0,1.000000,0.0,0.0,0.000000
50%,28.000000,14.454200,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,0.000000
75%,35.000000,31.275000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000
max,80.000000,512.329200,1.000000,8.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000

 Cinsiyet Dağılımı
Sex
0    843
1    466
Name: count, dtype: int64

 Benzersizler
[ 2.  0.  1. nan]

4-SATIR/SÜTUN İNDEKSLERİ VE FİLTRELEME (LOC, ILOC, BOOLEAN INDEXING)

In [ ]:
# iloc ile ilk 5 satır ve ilk 3 sütunu konuma göre seçer
print("\n iloc ile ilk 5 satır ve 3 sütun")
display(df.iloc[:5, :3])

# loc ve Boolean Indexing ile çoklu şartlı filtreleme
#1.sınıfta olan ve hayatta kalan yolcuları listeler
kurtulan_birinci_sinif = df.loc[(df['Pclass'] == 1) & (df['2urvived'] ==1)]
print(f"\n1. Sınıf Hayatta Kalan Sayısı: {len(kurtulan_birinci_sinif)}")


# isin() kullanarak filtreleme
liman_cq = df.loc[df['Embarked'].isin([1, 2]), ['Age', 'Fare']]
print("\n C ve Q Limanından Binen İlk 3 Yolcu")
display(liman_cq.head(3))

 iloc ile ilk 5 satır ve 3 sütun

              Age     Fare  Sex
Passengerid
1            22.0   7.2500    0
2            38.0  71.2833    1
3            26.0   7.9250    1
4            35.0  53.1000    1
5            35.0   8.0500    0

1. Sınıf Hayatta Kalan Sayısı: 136

 C ve Q Limanından Binen İlk 3 Yolcu

              Age    Fare
Passengerid
1            22.0   7.250
3            26.0   7.925
4            35.0  53.100

5-VERİ TEMİZLEME VE DÖNÜŞTÜRME (FILLNA, REPLACE, ASTYPE)

In [ ]:
# Orijinal veriyi bozmamak için kopya üzerinde çalışıyoruz
islenmis_df =df.copy()

#yaş sütununundaki eskik değerleri yaşın medyanı ile dolduracağız
yas_medyani = islenmis_df['Age'].median()
islenmis_df['Age'] = islenmis_df['Age'].fillna(yas_medyani)

# Kabin sütunundaki eksik değerlere 'Unknown' atıyoruz
islenmis_df['Parch'] =islenmis_df['Parch'].fillna("Unkown")

# Kategorik değerleri Türkçeleştirme
islenmis_df['Sex'] = islenmis_df['Sex'].replace({'female':'Kadin','male':'Erkek'})

#Sınıf sütununu sayısal değil de bir kategori/etiket olarak algılaması için string yapıyoruz
islenmis_df['Pclass'] = islenmis_df['Pclass'].astype(str)

6-HARİTALAMA VE MERKEZİLEŞTİRME

In [ ]:
#vektörel merkezileştirme

#bilet ücretlerinin (Fare) genel aritmetik ortalamasını hesaplıyoruz
ortalama_ucret = islenmis_df['Fare'].mean()
#bilet ücretinden ortalama ücreti çıkarıyoruz
islenmis_df['Centered_Fare'] = islenmis_df['Fare'] - ortalama_ucret


#yaş ve cinsiyete göre yolcunun hangi grupta yer alacağını belirleyen fonksiyon
def yolcu_grubu(satir):
  if satir ['Age'] < 18:
    return 'Cocuk'
  elif satir ['Sex'] =='Kadin':
    return 'Yetiskin_Kadin'
  else:
    return 'Yetiskin_Erkek'

#yolcu_grubu fonkisyonunu DataFrame in tüm satırlarına uygular
#axis='columns satır satır çalışması ve sütun değerlerine erişim sağlar
islenmis_df['Yolcu_Grubu'] = islenmis_df.apply (yolcu_grubu, axis='columns')

print("\n Yeni Yolcu Grubu Dağılımı")
print(islenmis_df['Yolcu_Grubu'].value_counts())
#value_counts(), sütundaki benzersiz değerlerin kaç kez tekrarlandığını söyler

 Yeni Yolcu Grubu Dağılımı
Yolcu_Grubu
Yetiskin_Erkek    1155
Cocuk              154
Name: count, dtype: int64

7- MODELLEME ÖNCESİ FEATURE VE TARGET AYRIMI

In [ ]:
#değişken belirleniyor
# modelin tahmin etmesini istediğimiz bağımlı değişkeni seçiyoruz
# 'Survived' sütunu yolcunun hayatta kalıp kalmadığını (0: Öldü, 1: Kurtuldu) temsil ediyoruz
y = islenmis_df['2urvived']

#girdiler seçiliyor
#modeli yolcunun durumunu tahmin etmek için kullanacağımız bağımsız değişkenleri seçiyoruz
#katkısı olmayan sütunları buraya dahil etmiyoruz
X = islenmis_df[['Pclass','Sex','sibsp','Parch','Fare','Embarked', 'Yolcu_Grubu']]


print("\n -Model Öcesi Kontrol-")

#1-Hedef değişkenin sınıf dağılımı
# normalize=True kullanarak hayatta kalanlar ile hayatını kaybedenlerin oranını yüzde olarak görüyoruz
#amacı veri setinde sınıf dengesizliği olup olmadığını anlamak
#örneğin verinin %99'u 0 olsaydı model sadece 0 tahmin ederek yanıltıcı yüksek başarı gösterebilirdi
print("y Dağılımı (sınıf dengesi kontrolü):")
print(y.value_counts(normalize=True))


#2-Girdi matrisinin x boyutu
# X.shape çıktısı satır sayısı, sütun sayısı formatında gelir
#amacı seçilen girdi sayısını doğrulamak ve satır kaybı olup olmadığını kontrol etmektir
print(f"\n2. Girdi Matrisi X Boyutu: {X.shape} ")


#3-eksik veri kontrolü
# X.isnull().sum() her sütundaki eksik değer sayısını verir,
#ikinci .sum() ise tüm tablodaki toplam eksik hücreyi sayar
#amacı birçok makine öğrenmesi algoritması NaN değerlerle çalışamaz
#çıktının 0 olması ve modelleme öncesi eksik veri kalmadığını garantiler
print("3. Kalan Eksik Veri Var Mı?: ", X.isnull().sum().sum())

 -Model Öcesi Kontrol-
y Dağılımı (sınıf dengesi kontrolü):
2urvived
0    0.738732
1    0.261268
Name: proportion, dtype: float64

2. Girdi Matrisi X Boyutu: (1309, 7)
3. Kalan Eksik Veri Var Mı?:  2